### ISSUE TITLE
apm/package.json needs to use an exact version (no ^caret semver range), or our `@atom-ide-community/atom-package-manager@2.5.0` needs to be unpublished

### ISSUE THREAD

**Issue by DeeDeeG** [atom-ide-community/atom#105]
VERY BRIEF SUMMARY: We should have an exact version for apm in `apm/package.json`. Version ranges can cause the wrong (broken) version to be installed. We should also consider un-publishing the `2.5.0` release.

---

BACKGROUND: The latest releases of our forked apm (`@atom-ide-community/atom-package-manager@2.5.0-atomic.2.1`) is technically a pre-release for `v2.5.0`, according to [semver](https://semver.org/#spec-item-9).

That means `npm install` is free to "bump" from `2.5.0-atomic.2.1` to `2.5.0` any time it wants to. The fact that it doesn't always do this is lucky. I got unlucky in my CI run here, and it installed the old one with broken line endings on Unix. So my "Linux" and "macOS Build" jobs failed: 
- https://dev.azure.com/DeeDeeG/b/_build/results?buildId=591&view=results
  - https://dev.azure.com/DeeDeeG/b/_build/results?buildId=591&view=logs&j=e2cf4b02-5697-54ad-cf7c-fc2a840d53af&t=e716fffa-162f-53e5-ffce-5e575d04822c&l=83

SOLUTION: We can either pin to an exact version in `apm/package.json`, or un-publish our `2.5.0` release, or both.

WORKAROUND: Bump the core `2.5.0` version to something newer like `2.5.2` (e.g. `2.5.2-atomic.1)` and DON'T publish a version of our forked apm with just the core version number, e.g. `2.5.2`. ONLY publish `[core]-atomic.[x]` releases.

_(FWIW I know publishing `2.5.0` was an accident that I could have easily done myself.)_

(If our real, stable releases are going to use what's technically a pre-release numbering scheme, then the non-prerelease versions will always take precedence and be preferred by `npm`. So publishing core-only release numbers breaks the ergonomics/convenience of using our forked package. And makes `npm install` unreliable.)

**Comment by aminya** [comment]
I pinned the version. This should be fixed now. Closing?

**Comment by DeeDeeG** [comment]
Yeah, this is solved with #103, thanks.

This [documentation](https://docs.npmjs.com/cli/unpublish) says unpublish doesn't work 72 hours after publishing, but we can contact npm support if we ever really needed to take something down.

At least deprecation might show a warning letting us know what happened. I kind of wish `script/bootstrap` didn't hide so much output. It makes everything a bit harder to debug.
