### ISSUE TITLE
Consider another CI approach rather than Azure DevOps

### ISSUE THREAD

**Issue by DeeDeeG** [atom-ide-community/atom#42]
Building Atom isn't that hard in real life. Why should it be harder in a predictable environment such as CI?

I propose that we should investigate other tried and true methods to build and test Atom.  I am personally familiar with Travis CI, and I find Github Actions a reasonably promising alternative (but I'm much less familiar with it).

Azure DevOps has this benefit: Upstream uses it.

And in my mind it has this downside: It's extremely complicated.

Maybe there is a better way.

We could do this in stages: Start by building on another CI in parallel with Azure. Then move on to building and testing on two CIs. Then move to mainly building/testing with the Non-Azure CI but using Azure DevOps for releases. Then ultimately do releases from the other CI.

If at any point we're comfortable with the transition being permanently split (such as keeping the code for doing releases on Azure DevOps, but validating on another CI), then we can just leave it there. So long as we are deliberate about it.

Or I could investigate on my personal fork in spare time. And report back the good news... or not bring it up again. :laughing:

**Comment by aminya** [comment]
Considering that the focus of this fork is on the end-user side of the things (See them [here](https://github.com/atom-ide-community/atom/projects)), I do not want us to spend more time on reinventing the wheel. 

We have a CI system that we are pretty happy with it. GitHub Actions is good for projects. All the other atom packages in this organization use that. See [here](https://github.com/atom-ide-community/atom-ide-datatip/blob/master/.github/workflows/ci.yml) for an example. But it does not have the capability and flexibility that Azure offers.

For example, the coaching system is not that developed, it lacks `templates`, and many other things. 

Thanks for the suggestion, but for big projects like Atom, Azure is very suitable.

**Comment by aminya** [comment]
I will close this for now. I look forward to simplifying some other things like `linting`, but that is less related to CI. see here for more plans: https://github.com/atom-ide-community/atom/projects
