### ISSUE TITLE
Updating Python 3 for all operating systems

### ISSUE THREAD

**Issue by aminya** [atom-ide-community/atom#51]
After we merged #46, it is now apparent that only Windows is using python 3. Should not we use python 3 for all operating systems? 

https://github.com/atom-ide-community/atom/blob/d87b59bf0fcdabd0a2e330ceaa513bc1ff21e72a/script/vsts/platforms/templates/preparation.yml#L39-L43

@DeeDeeG

**Comment by DeeDeeG** [comment]
We should simply drop the explicit Python 3 for Windows.

It doesn't matter which Python major version we use, so long as node-gyp is happy to use it. Python runs gyp, which then builds C++ code.

I don't think Python 2 or 3 is faster.

What's nice is to not have to specify it in our configs at all and use what's shipped with the Microsoft Hosted Agent (Ubuntu/Windows/macOS images from Microsoft).

**Comment by DeeDeeG** [comment]
I am interested in doing a "simplify the preparation phase" for htings like this, The goal: Cut out as many steps as we can and just run on what the image has in it. Give some thought and a reason why each thing that was dropped is okay to drop. Then merge to `master`. Obsoletes #44. I don't care quite so much if we are on Windows Server 2019 or not, simpler configs is more important than that.

No promises on when, but I'd like that to be the next main thing I do for this fork.

**Comment by DeeDeeG** [comment]
Various experimental branches at my personal fork: https://dev.azure.com/DeeDeeG/b/_build?view=runs&branchFilter=33%2C34

I don't really know if this will work, so I'm not posting them here yet until I feel some solid progress has been identified to post here. But feel free to look at the runs and the respective branches in the mean-time.

**Comment by DeeDeeG** [comment]
Clang vs GCC benchmarked; Neither necessarily makes faster apps: https://www.phoronix.com/scan.php?page=article&item=gcc10-clang10-x86

I'd strongly rather use GCC for simpler CI.

**Comment by aminya** [comment]
I do not support regressing to GCC. We should even try to use Clang on Windows and macOS, not the other way around! Other than having better runtime performance, Clang has so many more features. In the current CI, we do not install Clang any more. It is included in all the images. There is no need to use gcc.

**Comment by DeeDeeG** [comment]
I prefer GCC, because it is the default.

Performance is quite similar between GCC and Clang in a general sense, so I personally do not believe that Clang is substantially better for this use-case, unless we benchmark _Atom or its packages_ with the different compilers. Or if there are different bugs in the built app based on the given compiler.

That said, I don't need to get into a disagreement about it. So long as we can set the compiler to be one of them and find that it always builds correctly, I suppose I can live with either compiler.
