### ISSUE TITLE
Sign built Atom packages, or delete CI steps requiring code signing

### ISSUE THREAD

**Issue by DeeDeeG** [atom-ide-community/atom#8]
CI is failing on a step that tries to sign the built packages:

- Windows: https://dev.azure.com/atomcommunity/atomcommunity/_build/results?buildId=21&view=logs&j=4fbced83-508e-5fe0-c978-5c71ec0fc506&t=8ab1786f-98fc-5bc4-a8d0-c08e0675c13a&l=4873
  - `Error: The protocol "null" is not supported, cannot load "$(ATOM_WIN_CODE_SIGNING_CERT_DOWNLOAD_URL)"`
- macOS: https://dev.azure.com/atomcommunity/atomcommunity/_build/results?buildId=15&view=logs&j=e2cf4b02-5697-54ad-cf7c-fc2a840d53af&t=daf62785-c7df-523f-33d8-78a3cf89d33a&l=4863
  - `Error: The protocol "null" is not supported, cannot load "$(ATOM_MAC_CODE_SIGNING_CERT_DOWNLOAD_URL)"`

We should set a secret "code signing cert" download URL in the env variables of our CI so that these steps can pass... Or edit the code so we don't even try to sign the code.

<details><summary>Thoughts on security and keeping the signing cert secret, if we get one (click to expand):</summary>

(We need to keep this secret only amongst maintainers, or else anyone can impersonate our digital "signature". Not sure if this is a big deal after all, because what are the stakes to impersonating us? But yeah, we should keep it secret in case we find out the stakes were higher than we thoughts, e.g. security problems for our users).

(Not signing might break things on macOS? I know they started expecting code to be signed by a known developer over the past few years. Then again, playing ball with Apple usually costs money/involves having an Apple Developer account, so I'm not sure whether or not this is doable for free.)

</details>

I'd like to try to figure out (or just ask) what format or standard this signing certificate takes at upstream, so we can make one for Atom Community and properly sign ours.

**Comment by aminya** [comment]
We should either remove them or use the same thing that upstream uses. @darangi @smashwilson @lkashef might now about that.

We do not have a budget for purchasing a certificate at the moment.

**Comment by aminya** [comment]
I made the code signing optional in https://github.com/atom-ide-community/atom/pull/9. We need to set it to `false`, and upstream needs to set it to `true`

**Comment by DeeDeeG** [comment]
For the record, here is some relevant documentation for properly code signing an app on Windows or macOS:

- https://docs.microsoft.com/windows-hardware/drivers/dashboard/get-a-code-signing-certificate
- https://developer.apple.com/support/code-signing/

Perhaps in the future, we or other forks of Atom (or just folks developing desktop apps in general) might be interested in this.

**Comment by DeeDeeG** [comment]
I'm looking into if there might be a simpler fix for this. I haven't gotten it working yet, but I've done a few CI runs and it feels close to being solved.

---

First idea: Set `ATOM_WIN_CODE_SIGNING_CERT_DOWNLOAD_URL` (and other related environment variables) to be blank strings, through the Azure Pipelines web UI.

---

Second idea:

I noticed [some](https://github.com/atom/atom/blob/0fe5533/script/lib/code-sign-on-mac.js#L16-L25) [code](https://github.com/atom/atom/blob/0fe5533/script/lib/code-sign-on-windows.js#L8-L17) in the repo that already skips signing if the relevant variables aren't set in the environment.

(variables `ATOM_WIN_CODE_SIGNING_CERT_DOWNLOAD_URL`, `ATOM_WIN_CODE_SIGNING_CERT_PATH`, etc.)

These variables should be empty in our CI, except for that the `$(some_var_here)` syntax in Azure Pipelines YAML files doesn't evaluate to an empty string if no value is found, it evaluates to literally the string "`$(some_var_here)`", dollar signs `$` and parentheses `()` included. Azure Pipelines calls this "macro syntax".

https://docs.microsoft.com/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#understand-variable-syntax

Somewhat related: https://docs.microsoft.com/azure/devops/pipelines/process/expressions?view=azure-devops#variables

We should use "runtime expression syntax": `$[variables.some_var_here]`.

This becomes blank if no value is found. I think that's what Atom's upstream developers expected, they just haven't tested without those variables set, so it never was an issue like it is for us now.

**Comment by DeeDeeG** [comment]
Simply setting the vars to be blank (`ATOM_WIN_CODE_SIGNING_CERT_DOWNLOAD_URL=""`) in CI works for skipping code signing on macOS/Windows, but does not skip notarization on macOS. So that step still errors out on macOS builds.

There are two approaches I can think of:
- Make notarization skip if code signing was skipped (rewrite the javascript files)
- Condition both steps in CI on whether the variables are truthy (rewrite CI config files).
